---
# This playbook contains common plays that will be run on all nodes.

- name: Configure zabbix_confige file
  copy: src=openstack_status_zabbix.conf dest=/etc/zabbix/zabbix_agentd.conf.d/

- name: copy script
  copy: src=openstack-discovery dest=/opt/openstack-discovery 

- name: chmod script
  shell: chmod +x /opt/openstack-discovery 

- name: restart zabbix_agent
  service: name=zabbix-agent state=restarted enabled=yes

