---
# This playbook contains common plays that will be run on all nodes.

- name: Configure zabbix_confige file
  copy: src=openstack_status_zabbix.conf dest={{ zabbix_include_dir }}
  notify:
    - restart zabbix-agent

- name: copy script to dest
  copy: src=openstack-discovery dest=/opt/openstack-discovery mode=u+x backup=yes 

