# This playbook deploys the whole application stack in this site.

- name: install megacli
  hosts: all
  remote_user: root

  roles:
    - megacli


- name: copy zabbix ceph UnsafeUserParameters config
  hosts: ceph-osd
  remote_user: root

  roles:
    - common
