---
# This playbook contains common plays that will be run on all nodes.

- name: Configure zabbix_confige file
  copy: src=ceph_stauts_zabbix.conf dest={{ zabbix_include_dir }}
  notify:
    - restart zabbix-agent

- name: copy script
  copy: src=ceph-status.sh dest=/opt/ceph-status.sh mode=u+x backup=yes 

- name: apt install bc
  apt: name=bc state=present update_cache=yes
