---
# This playbook contains common plays that will be run on all nodes.

- name: Configure zabbix_confige file
  copy: src=zabbix_agentd.conf dest=/etc/zabbix/zabbix_agentd.conf

- name: copy script
  copy: src=openstack-discovery dest=/opt/openstack-discovery 

- name: chmod script
  shell: chmod +x /opt/openstack-discovery 

- name: restart zabbix_agent
  copy: src=zabbix_agentd.conf dest=/etc/zabbix/zabbix_agentd.conf
  tags: zabbix_agent
  notify: restart zabbix_agent

