---
# This playbook contains common plays that will be run on all nodes.

- name: Configure sources file
  copy: src=sources.list dest=/etc/apt/sources.list
  tags: sources file 

- name: add gpg
  command: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C407E17D5F76A32B
  command: sudo gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys

- name: apt install megacli megactl megaraid-status
  apt: pkg=megacli state=present update_cache=yes
  apt: pkg=megaraid-status state=present update_cache=yes
  apt: pkg=megactl state=present update_cache=yes

- name: Configure zabbixagentd conf
  copy: src=zabbix_agentd.conf dest=/etc/zabbix/zabbix_agentd.conf

- name: Configure raid.phy conf
  copy: src=raid_disk_status.conf dest=/etc/zabbix/zabbix_agentd.conf.d/

- name: creater dir
  shell: mkdir -p /etc/zabbix/scripts/raid_disk_status/

- name: copy script
  copy: src=raid.py dest=/etc/zabbix/scripts/raid_disk_status/raid.py

- name: chmod script
  shell: chmod +x /etc/zabbix/scripts/raid_disk_status/raid.py

- name: rstart zabbix_agentd 
  service: name=zabbix-agent state=restarted enabled=yes
